apiVersion: v1
kind: Service
metadata:
  name: metastore
  labels:
    app: trino-analytics
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
  selector:
    app: metastore